# Generated by Django 5.2.4 on 2025-11-15 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("import", "Import DICOM Files"),
                            ("send", "Send DICOM Series"),
                            ("test_connection", "Test Destination Connection"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was initiated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the action was completed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the operation",
                        max_length=10,
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        blank=True,
                        help_text="Patient name from DICOM metadata",
                        max_length=255,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True,
                        help_text="Patient ID from DICOM metadata",
                        max_length=64,
                    ),
                ),
                (
                    "study_instance_uid",
                    models.CharField(
                        blank=True, help_text="Study Instance UID", max_length=64
                    ),
                ),
                (
                    "series_instance_uid",
                    models.CharField(
                        blank=True, help_text="Series Instance UID", max_length=64
                    ),
                ),
                (
                    "series_description",
                    models.CharField(
                        blank=True,
                        help_text="Series description from DICOM metadata",
                        max_length=255,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        help_text="DICOM modality (CT, MR, XR, etc.)",
                        max_length=16,
                    ),
                ),
                (
                    "instance_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of DICOM instances in the series",
                        null=True,
                    ),
                ),
                (
                    "bytes_transferred",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total bytes sent for this transfer (successful sends)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if the operation failed"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional operation details (duration, file paths, etc.)",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        help_text="DICOM destination for send operations",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="destinations.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Log",
                "verbose_name_plural": "Transfer Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="dicom_api_t_user_id_975bb5_idx",
                    ),
                    models.Index(
                        fields=["status", "-timestamp"],
                        name="dicom_api_t_status_90ecad_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="dicom_api_t_action_3ee0fc_idx",
                    ),
                ],
            },
        ),
    ]
