# Generated by Django 5.2.4 on 2025-11-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dicom_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique identifier for grouping transfers initiated together",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="files_failed",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of files that failed to transfer"
            ),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="files_succeeded",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of files successfully transferred"
            ),
        ),
    ]
