# Generated by Django 5.2.4 on 2025-11-15 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-friendly identifier (e.g., 'PACS Alpha')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "ae_title",
                    models.CharField(
                        help_text="AE Title of the destination DICOM application",
                        max_length=16,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Hostname or IP address of the destination",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=104, help_text="Port number for DICOM service"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the destination"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this destination is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this destination",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DICOM Destination",
                "verbose_name_plural": "DICOM Destinations",
                "ordering": ["name"],
            },
        ),
    ]
